#!/usr/bin/env bash

set -e

cd "$(dirname $0)"/..
. ./script/env.sh

# create the user's bin directory
mkdir -p ~/bin

# link dot
ln -sf $(pwd)/bin/dot ~/bin/

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do bash "${installer}" ; done

