#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..
. ./script/env.sh

if [ $1 ]
then
  fish ./$1/install.fish
else
  # find the installers and run them iteratively
  find . -name install.fish | while read installer ; do fish "${installer}" ; done
fi

