#!/usr/bin/env bash
#
# Run all dotfiles updaters.

set -e

cd "$(dirname $0)"/..
. ./script/env.sh

# find the updaters and run them iteratively
find . -name update.fish | while read updater ; do fish "${updater}" ; done

