export DE="lxde"
export DESKTOP_SESSION="LXDE"
export XDG_MENU_PREFIX="lxde-"

export VISUAL="emacs"
export EDITOR="e"
export BROWSER="firefox"

export PATH="$HOME/bin:$HOME/perl5/bin:$PATH"
export MANPATH="$HOME/perl5/man/man:/usr/local/man:$MANPATH"

export PERL_MB_OPT="--install_base \"/home/loic/perl5\""
export PERL_MM_OPT="INSTALL_BASE=/home/loic/perl5"
export PERL5LIB=/home/loic/perl5/lib/perl5

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# gnupg
export GPG_TTY=$(tty)

if [ -f ~/.gpg-agent-info ]; then
   . ~/.gpg-agent-info
else
    unset SSH_AGENT_PID
    if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
        export SSH_AUTH_SOCK="${HOME}/.gnupg/S.gpg-agent.ssh"
    fi
fi

# OpenBSD's packages
if [[ $(uname) == OpenBSD ]]; then
   export PKG_PATH=ftp://ftp.fr.openbsd.org/pub/OpenBSD/snapshots/packages/`machine -a`/
fi
