directory: ~/Music/Library/
library: ~/Music/musiclibrary.blb
asciify_paths: true
per_disc_numbering: true

paths:
    default: $albumartist/$album%aunique{}/$disc-$track - $albumartist - $title
    singleton: Non-Album/$artist/$artist - $title
    comp: Compilations/$album%aunique{}/$disc-$track - $artist - $title

import:
    move: yes

plugins: info missing duplicates convert scrub ftintitle play fetchart lastgenre replaygain embedart smartplaylist

play:
    command: vlc -I rc

fetchart:
    enforce_ratio: yes
    minwidth: 300
    maxwidth: 1000
    sources: itunes * wikipedia google fanarttv

lastgenre:
    canonical: '~/.config/beets/genres-tree.yaml'
    fallback: ''
    force: yes
    prefer_specific: no
    source: artist
    whitelist: '~/.config/beets/genres.txt'

replaygain:
    backend: gstreamer
    overwrite: yes

embedart:
    auto: no

smartplaylist:
    relative_to: ~/Music/Playlists
    playlist_dir: ~/Music/Playlists
    playlists:
        - name: _all.m3u
          query: ''

        - name: _favorites.m3u
          query: 'favorite:true'

        - name: quality-low.m3u
          query: 'bitrate:..319999'

        - name: quality-standard.m3u
          query: '^bitrate:..319999 ^format:flac'

        - name: quality-high.m3u
          query: 'format:flac'

        - name: genre-afrobeat.m3u
          query: 'genre:afrobeat ^comp:true'

        - name: genre-electronic.m3u
          query: [ 'genre:electronic ^comp:true'
                 , 'genre:electro ^comp:true'
                 , 'genre:house ^comp:true'
                 , 'genre:techno ^comp:true'
                 ]

        - name: genre-new-wave.m3u
          query: 'genre:"new wave" ^comp:true'

        - name: genre-rap.m3u
          query: 'genre:rap ^comp:true'

        - name: genre-rnb.m3u
          query: 'genre:r&b ^comp:true'

        - name: genre-soul.m3u
          query: 'genre:soul ^comp:true'
