directory: ~/Music/good
library: ~/Music/good/musiclibrary.blb
asciify_paths: true
per_disc_numbering: true

paths:
    default: $albumartist/$album%aunique{}/$disc-$track - $albumartist - $title
    singleton: Non-Album/$artist/$artist - $title
    comp: Compilations/$album%aunique{}/$disc-$track - $artist - $title

import:
    move: yes

plugins: info missing duplicates convert scrub ftintitle play fetchart lastgenre replaygain embedart smartplaylist

play:
    command: vlc -I rc

fetchart:
    enforce_ratio: yes
    minwidth: 300
    maxwidth: 1000
    sources: itunes * wikipedia google fanarttv

lastgenre:
    canonical: '~/.config/beets/genres-tree.yaml'
    fallback: ''
    force: yes
    prefer_specific: yes
    whitelist: '~/.config/beets/genres.txt'

replaygain:
    backend: gstreamer
    overwrite: yes

embedart:
    auto: no

smartplaylist:
    relative_to: ~/Music/good
    playlist_dir: ~/Music/playlists
    playlists:
        - name: _favorites.m3u
          query: 'favorite:true'

        - name: rap.m3u
          query: 'genre:rap format:flac
          ^albumartist:"young fathers" ^albumartist:"public enemy"
          ^album:"greatest hits" ^album:"best of"
          ^comp:true'

        - name: groove.m3u
          query: ['albumartist:abra', 'albumartist:"blood orange"', 'albumartist:kelela', 'albumartist:kaytranada',
          'albumartist:"syd"',
          'album:"doing it in lagos" albumartist+ album+ track+']

        - name: low-res.m3u
          query: ['format:mp3 bitrate:..319999', 'format:acc bitrate:..255999']

        - name: cd-quality.m3u
          query: 'format:flac bitdepth:16'

        - name: hi-res.m3u
          query: 'format:flac bitdepth:24'
