directory: ~/Music
library: ~/Music/musiclibrary.blb
asciify_paths: true
per_disc_numbering: true

paths:
    default: $albumartist/$album%aunique{}/$disc-$track - $albumartist - $title
    singleton: Non-Album/$artist/$artist - $title
    comp: Compilations/$album%aunique{}/$disc-$track - $artist - $title

import:
    move: yes

plugins: info missing duplicates convert scrub ftintitle play fetchart lastgenre replaygain embedart smartplaylist

play:
    command: vlc -I rc

fetchart:
    enforce_ratio: yes
    minwidth: 300
    maxwidth: 1000
    sources: itunes * wikipedia google fanarttv

lastgenre:
    canonical: '~/.config/beets/genres-tree.yaml'
    fallback: ''
    force: yes
    prefer_specific: no
    source: artist
    whitelist: '~/.config/beets/genres.txt'

replaygain:
    backend: gstreamer
    overwrite: yes

embedart:
    auto: no

smartplaylist:
    relative_to: ~/Music/playlists
    playlist_dir: ~/Music/playlists
    playlists:
        - name: _favorites.m3u
          query: 'favorite:true'

        - name: bad-quality.m3u
          query: [ 'format:mp3 bitrate:..319999'
                 , 'format:acc'
                 ]

        - name: good-quality.m3u
          query: 'format:flac'

        - name: afrobeat.m3u
          query: 'genre:afrobeat bitrate:320000.. ^comp:true'

        - name: electronic.m3u
          query: [ 'genre:electronic bitrate:..319999'
                 , 'genre:electro bitrate:..319999'
                 , 'genre:house bitrate:..319999'
                 , 'genre:techno bitrate:..319999'
                 ]

        - name: new-wave.m3u
          query: 'genre:"new wave" bitrate:320000.. ^comp:true'

        - name: rap.m3u
          query: 'genre:rap bitrate:320000.. ^comp:true'

        - name: rnb.m3u
          query: 'genre:r&b bitrate:320000.. ^comp:true'

        - name: soul.m3u
          query: 'genre:soul bitrate:320000.. ^comp:true'
